[tools]
python = "3.12"

[tasks]
setup = "pip install -r requirements.txt"
db-init = "python scripts/init_db.py"
db-seed = "python scripts/seed_db.py"
dev = "streamlit run app/main.py"
create-template = "python scripts/crear_plantilla.py"
create-admin = "python scripts/crear_admin.py"