services:
  - type: web
    name: control-documental-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    # Encadenamos los scripts con && antes de iniciar Streamlit
    startCommand: python scripts/init_db.py && python scripts/seed_db.py && streamlit run app/main.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: control-documental-db
          property: connectionString

databases:
  - name: control-documental-db
    plan: free
    databaseName: controldb
    user: dbuser